### ISSUE TITLE
Use configmap instead of profile URL

### ISSUE THREAD

**Issue by sergioatom** [pingidentity/pingidentity-devops-getting-started#146]
**Is your feature request related to a problem? Please describe.**
My k8s cluster does not have outside access and therefore retrieving a profile from a git url is not a valid option. Also it would make it hard to maintain multiple environment configs

**Describe the solution you'd like**
https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/20-kubernetes/04-clustered-pingaccess/env_vars.pingaccess-engine#L1

Expose all files via kubernetes configmaps

**Describe alternatives you've considered**
* Manually create _configmap_ and expose it with _file:/// syntax_ 
* GCP or AWS buckets

**Comment by samir-gandhi** [comment]
Hi @sergioatom 
This is a good idea, but we've not recommended the path forward on it because it would become quite complex on yamls (especially with our other products), and some of our files from profiles can be bigger than the allotted space in a configmap. 
Note, it may work just fine for this PingAccess example you mention. However, I think a better/more consistent approach would be for you to add the profile directly into the image. 

Here's what I mean:
1. git clone the server-profile repo on your machine. 
2. make a dockerfile to build the profile into the image. 
```
FROM pingidentity/pingaccess:2010-6.1.3
COPY pingidentity-server-profiles/pa-clustering/pingaccess /opt/in
```
3. 
```
docker build -t sergioatom/pingaccess:6.1.3 .
docker push sergioatom/pingaccess:6.1.3
```
And this can be used for the engine, then you can remove the profile url vars. 
4. The admin has one file more than the engine, this file may be a good candidate for a configmap, or for consistency you could go through the same process and add the `pingaccess-admin/instance/data/start-up-deployer/data.json` to a _separate_ admin image. 

```
FROM pingidentity/pingaccess:2010-6.1.3
COPY pingidentity-server-profiles/pa-clustering/pingaccess /opt/in
COPY pingidentity-server-profiles/pa-clustering/pingaccess-admin/instance/data/start-up-deployer/data.json /opt/in/instance/data/start-up-deployer/data.json
```
```
docker build -t sergioatom/pingaccess-admin:6.1.3 .
docker push sergioatom/pingaccess-admin:6.1.3
```

**Comment by sergioatom** [comment]
Thank you for the example @samir-gandhi

I will look into creating our own images.
