### ISSUE TITLE
Unable to access Ping Directory Administrative Console

### ISSUE THREAD

**Issue by saikiranchalla1** [pingidentity/pingidentity-devops-getting-started#22]
**Describe the bug**
I get a 404 Not found error when trying to access the Administrative console.

**To Reproduce**
This behavior can be seen when running the Ping Directory locally on docker:
1) docker run \
           --name pingdirectory \
           --publish 1389:389 \
           --publish 8443:443 \
           --detach \
           --env SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-getting-started.git \
           --env SERVER_PROFILE_PATH=pingdirectory \
           pingidentity/pingdirectory
2) Access `https://localhost:8443/console` from the browser.

**Expected behavior**
The administrative console should be displayed

**Screenshots**

**Environment:**
 - Github Repo: pingidentity-devops
 - Docker Container: pingdirectory
 - Cloud Environment: Localhost and VMSS on Azure cloud

**Additional Info**
N/A

**Comment by saikiranchalla1** [comment]
@samirgandhi19 @tsigle I couldn't find enough details on the Gitbooks here: https://pingidentity-devops.gitbook.io/devops/. It is possible that I'm missing something important.

**Comment by arnaudlacour** [comment]
Your step #2 as described in the issue is not going to work by design.
If you were installing the product from the ZIP file, then by default there is an administration console running. Realistically, only one administration console is needed in a scaled environment. To avoid duplicating the administrative console with every PingDirectory container we disable it by default in our Docker image.

You have 2 ways to get to the access console:
 1 - run the admin console container
https://pingidentity-devops.gitbook.io/devops/docker-images/ping_data_console
 2 - enable the admin console in your directory container
```
dsconfig set-connection-handler-prop \
    --handler-name "HTTPS Connection Handler" \
    --set enabled:false \
    --set web-application-extension:Console
dsconfig set-connection-handler-prop \
    --handler-name "HTTPS Connection Handler" \
    --set enabled:true
```
