### ISSUE TITLE
Root step-down

### ISSUE THREAD

**Issue by saikiranchalla1** [pingidentity/pingidentity-devops-getting-started#23]
**Is your feature request related to a problem? Please describe.**
As a security best practice pods are not allowed to run as root users. Since Ping's containers need access to /opt directory it is preventing them from running on K8s cluster.

**Describe the solution you'd like**
Ability to run Ping containers as non-root users.

**Describe alternatives you've considered**
N/A

**Additional context**
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups (this didn't work for the Ping containers)

**Comment by arnaudlacour** [comment]
Thanks for opening this ticket. We are aware of this ask and we are currently considering different strategies to implement this in a way that would not be a nightmare when it comes to managing bind mounts.

**Comment by saikiranchalla1** [comment]
Thank you very much.

Is there a timeline for this?

**Comment by arnaudlacour** [comment]
Granted this took entirely too long but the images may be started in unprivileged mode by passing the PING_CONTAINER_PRIVILEGED=false environment variable. 
a ping:identity user spec is created when that is the case and the file permissions are updated to allow the container to function.
PING_CONTAINER_UID and PING_CONTAINER_GID can also be passed to specify a user and group ID. Otherwise the default user id is 9031 and the default group id is 9999.

It is also possible to provide the docker container with user spec (uid:gid) to execute as in which case the container will not use set uid and run as-is.
