### ISSUE TITLE
Unable to use private Git repo

### ISSUE THREAD

**Issue by saikiranchalla1** [pingidentity/pingidentity-devops-getting-started#25]
**Describe the bug**
As per the Gitbook, the SERVER_PROFILE_URL is a Git URL that is cloned by the container at the time of start-up. Since this configuration contains sensitive information, it is ideal that we store this in a private repo on organization's SVN (VSTS).
When using the private repo, the container fails to start because it is unable to authenticate to the private Git repo. 

**To Reproduce**
1. create a Kube deployment for Ping Directory with environment variable (SERVER_PROFILE_URL) set to a private GitRepo.
2. Deploy the container.
**Expected behavior**
Should clone the Git Repo and start successfully.

**Screenshots**

**Environment:**
 - Github Repo: [ping-directory, server-profile, docker-builds]
 - Docker Container: pingdirectory
 - Cloud Environment: Azure

**Additional Info**
Add any other information about the problem here.

**Comment by tsigle** [comment]
Thanks for filing an issue.

In order to perform a git clone on a priviate git repo, you can provide your git username and access key to pull the contents.  It would look something like:

   https://username:password@github.com/username/repository.git

Where password is either your password (not optimal or secure) or a git access key, which you should be able to get via the git "personal access tokens". You can find those under your github personal settings-->Developer Setttings-->Personal access tokens.

Try that out and let us know.

**Comment by saikiranchalla1** [comment]
Thank you very much.
Does it have to be a Git repo? Can I not use something like a blob store to securely place my configuration?

Also, is there a way to pass encryption certificate to the container?

**Comment by tsigle** [comment]
Currently, it needs to be a git repo unless you have local access to the configuration locally and mount it as a docker volume to /opt/in on the container.  You can see examples of how to mount a volume to /opt/in on the docs:

  https://pingidentity-devops.gitbook.io/devops/getting-started-examples/10-docker-standalone/01-pingdirectory#using-a-local-volume

Closing this issue, as it's a git related issue to private repos

**Comment by arnaudlacour** [comment]
it is worth noting that if you want to use your own subversion or private Git repository, you can simply publish a server profile that overrides `hooks/14-get-remote-server-profile.sh`.
In that shell script, you can implement the logic you need to pull your configuration from your subversion or other repo such as a plain S3 bucket for example.
