### ISSUE TITLE
Approving request from notification tray bypasses biometrics

### ISSUE THREAD

**Issue by roxasthenobody98** [pingidentity/pingidentity-devops-getting-started#338]
PingID App V.1.23.0(13063)

Device: Samsung Galaxy Note20 Ultra 5G
Android Version: 12
Baseband: N986USQU2EVA9
Android Security Patch: 02/01/2022

When an incoming authentication request is delivered to the device, a notification is created with the buttons Approve and Deny.

Tapping approve in the notification bypasses biometrics and sends an approved request to the application requesting MFA. If the request is answered from inside the PingID App instead, it will prompt for biometrics.

This works regardless of if I unlock my device with PIN or Bio, and also works no matter how long my phone has been unlocked for.

**Comment by arnaudlacour** [comment]
this is the expected behavior, access to the notification tray requires the device to be unlocked and serves as a shortcut.

In the future, if you need quicker turnaround time for replies about product issues, it is recommended that you [open a support ticket with Ping Identity Support](https://support.pingidentity.com/s/contactsupport)
