### ISSUE TITLE
I cant register for a devops account

### ISSUE THREAD

**Issue by claylehman** [pingidentity/pingidentity-devops-getting-started#523]
I go here: https://devops.pingidentity.com/how-to/devopsRegistration/

but the signin/login process is broken.

WHen i login i get redirected to an error page.

<img width="672" alt="image" src="https://github.com/pingidentity/pingidentity-devops-getting-started/assets/40699759/20b9e48c-0fce-4eae-80e1-ed7b374099a2">

i need a devops license key to run a local docker ping server for testing

**Comment by PingDavidR** [comment]
Greetings, @claylehman!  I'm sorry you encountered a problem getting signed up.  Just to confirm, I went through the enrollment process as outlined on our portal.  I went to the sign-up link (https://www.pingidentity.com/en/account/register.html) and registered a new email address.  I received the confirmation email and validated my account, where I was able to provide my name and phone number, along with signing up for the developer program.  After logging in, I was able to register for the DevOps program (the screenshot at https://devops.pingidentity.com/how-to/devopsRegistration/ is dated, but it is still clear that there is a button for registering for the DevOps program).  I got my DevOps user and key in my email a few minutes later.

The SSO issue might be related to the email you used to attempt to register for the program.  The DevOps team does not handle the Salesforce IDs, you would need to contact your support representative for help there.

**Comment by claylehman** [comment]
Thank you for the info! i am not using salesforce, that was just when i tried to login to the devops area.  I am going to try a new email address from scratch with the URL you have here and see if i have better luck and report back

**Comment by claylehman** [comment]
strange. with a new account im still getting redirected to an error page... see this loom video...
https://www.loom.com/share/56064ca4d7e249a38c12837acabb2b63?sid=2b926e72-9b59-4303-bcb1-a771120f058f

**Comment by PingDavidR** [comment]
Try a private browser tab.  I think you have some credentials cached somehow.

**Comment by claylehman** [comment]
Thanks for helping me i really appreciate it!  I started over and did the full flow in chrome "incognito" and now it says my user/password is bad, and if i click "reset" it says the account doesnt exist.  I dont know what im doing wrong... i feel like im losing my mind

https://www.loom.com/share/478e29c916204a618fc89de951c3a9c4?sid=c3c595ee-057b-4924-827f-619d65934b52

**Comment by PingDavidR** [comment]
That is weird indeed.  Let me do some checking on my end - could be a timing issue or something else.  Seems you are there from what I can see.  The fact you got the confirmation email points to it being registered in our backend, so I can't imagine what could be breaking down somewhere.

**Comment by PingDavidR** [comment]
OK, good news & bad news.  After my initial success, a subsequent trip to login to Ping's portal resulted in me receiving the  same errors you were seeing.  I was unable to login with my new credentials, and an attempt to reset the password gave me the "email not registered" error.  I am investigating where to route this issue internally, and will keep you updated.  Thanks for your patience!

**Comment by claylehman** [comment]
glad its not just me :D thanks for looking into this

**Comment by PingDavidR** [comment]
Seems it was an internal system that had some issues yesterday.  Try again this morning - I was able to login & register an account just now.

**Comment by claylehman** [comment]
interesting.... I just tried and registered a new account and I am back to my login getting redirected to an SSO error page now? 

<img width="1084" alt="image" src="https://github.com/pingidentity/pingidentity-devops-getting-started/assets/40699759/fbf6c0b7-254c-40ba-ab4f-7a1b4823c246">

**Comment by PingDavidR** [comment]
Thanks for your patience.  I was unable to dig on this yesterday.  

I did some further testing this morning with a fresh account.  I found a path that worked and one that does not.  If this fails to help you, I think I'll have to hand you off to sales support for further help, as the problem lies with processes & integration into the user database, something which my team does not have control.  You can use my steps as a means of reaching out to them with what we know & don't know.

- Created new email address.
- Launched incognito window
- Went to pingidentity.com and clicked “Sign On”

Here's where it gets interesting, and it's something I will take up internally with the owners of this process.  If I continue in the default flow and provide the new email address, it assumes I have credentials and I am not given an option to enroll.  So, I click _**Legacy Support Login**_, which gives me the option to **Create Account** at the bottom (screenshot 1, all screenshots are in the attached _enroll.zip_ file).

- Confirm email & password, click **Submit** (screenshot 2)
- I received the confirmation email and opened the link sent in an incognito window & completed my profile (screenshot 3).
- Click **Submit** and get confirmation (screenshot 4)
- The link on the success page takes me to the legacy screen again.  If I use this screen, it fails.  (Screenshot 5) (It is at this point I want to engage our team internally - if it's not going to work, we don't need to redirect here)
- Close the browser window (probably not necessary, but I was being thorough).
- I opened a new incognito window, returned to **pingidentity.com** and clicked **Sign On**.
- In this default flow screen, I entered my email and clicked **Continue**.
- I was sent a confirmation email with a one-time verification link, which I copied and opened in the same incognito window
- I provided my password, checked the reCAPTCHA box and clicked **Sign on** (screenshot 6)
- I’m in!  I can click the **Register for DevOps Program** button.  (Screenshot 7)
- I received confirmation and the email with my credentials (screenshot 8 & 9)

[enroll.zip](https://github.com/pingidentity/pingidentity-devops-getting-started/files/13675189/enroll.zip)

**Comment by PingDavidR** [comment]
@claylehman The internal team has identified 6 email addresses you have tried to use, and none are linked to an account (something they are investigating).  To get you unstuck, they can set you up manually, but wanted to know if there was one address in particular you would want to use... any preference?

**Comment by claylehman** [comment]
that would be amazing! my preference would be either clay@lehmansoftware.com or clay+ping@lehmansoftware.com

**Comment by PingDavidR** [comment]
any word here?  I want to make sure this didn't fall through with all the holiday leave upon us.

**Comment by claylehman** [comment]
Thanks for checking... ijust tried to login with my two emails listed above and got the error soon. i didnt try the workaround flow b/ci thought they were going to manually fix one of my accounts, i can if you want me to try that

**Comment by PingDavidR** [comment]
let's try the work around just for grins while we wait.  I'll follow up on my end

**Comment by claylehman** [comment]
i was able to get in with the workaround. nice! thank you so much for the info.

**Comment by PingDavidR** [comment]
HAPPY DANCE!  Glad to hear it.  I'll let them know.

**Comment by PingDavidR** [comment]
we are going to continue to identify the issue & correct things on this end, but for now going to close this issue since you were able to get your DevOps credentials.  Please reach out with a new issue if you encounter problems in the future.

**Comment by calvinwangjx** [comment]
Hi,@PingDavidR, I got the same error page and need your help on this issue. I'll get the error page if I use "Legacy Support Login" while I'll go to console.pingone.com if I just logon normally. I cannot access to Register for DevOps Program button. Thanks.
![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/17682283/f319e3ea-b4f1-4229-b860-6c33ab1a0df5)
![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/17682283/90740fee-5999-404c-83d3-719035aedd66)

**Comment by PingDavidR** [comment]
So, @calvinwangjx after getting the console, what do you see when you go to "My Account?"

![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/92101226/38a1ef27-7d2f-48ec-9d69-d0389685bb79)
